# Generated by Django 6.0.3 on 2026-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
    ]
